# Generated by Django 5.0.1 on 2024-01-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='content',
            name='src',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
