# Generated by Django 5.0.1 on 2024-01-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentApi', '0002_content_description_content_src_content_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='media_type',
        ),
    ]
