# Generated by Django 5.0.1 on 2024-01-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentApi', '0003_remove_content_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='src',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
