# Generated by Django 5.0.1 on 2024-01-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentApi', '0004_alter_content_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='public',
        ),
    ]
